### ISSUE TITLE
cannot import name 'Deeplabv3'

### ISSUE THREAD

**Issue by 46159100** [bubbliiiing/deeplabv3-plus-keras#1]
python predict.py
Traceback (most recent call last):
  File "predict.py", line 7, in <module>
    from deeplab import Deeplab
  File "E:\Code\Semantic Segmentation\deeplabv3-plus-keras-main\deeplab.py", line 8, in <module>
    from nets.deeplab import Deeplabv3
ModuleNotFoundError: No module named 'nets.deeplab'

**Comment by bubbliiiing** [comment]
根目录的问题噢。

**Comment by 46159100** [comment]
OK,谢谢帮助,已经解决
